config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations'
        }
  namespace :vendors do
    get 'home/index'
  end
  get '/admin', to: 'admins#index'
  resources :products
  resources :vendors
  root 'home#index'
  resources :orders
  post "/add_orderables", to: 'orders#add'
  post "/remove_orderables", to: 'orders#remove'
  get '/vendorproduct/:id', to: 'vendors#show_product', as: 'vendorproduct'
end

app/views/partials/_adminNavbar.html.erb
<div class="header-bg">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2">
        <%= link_to root_path, class: "home-link" do %>
          <h2 class="logo-design px-3">S.Online</h2>
        <% end %>
      </div>
      <div class="col-md-6 ">
      </div>
      <div class="col-md-4 text-md-end header-cred-design">
        <% if user_signed_in? %>
          <%= link_to "Logout" , destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} , class:"home-login-link"%>
        <% else %>
          <%= link_to "Login" , new_user_session_path , class:"home-login-link me-3"%>
          <%= link_to "Register" , new_user_registration_path , class:"home-login-link"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_adminSidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary" style="width: 280px;">
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= link_to "Admin Elements" ,admin_path ,class:"nav-link active" %>
    </li>
    <li>
      <%= link_to "Products", root_path ,class:"nav-link  " %>
    </li>
    <li>
      <%= link_to "Orders", root_path ,class:"nav-link " %>
    </li>
    <li>
      <%= link_to "Vendors", root_path ,class:"nav-link" %>
    </li>
  </ul>
</div>

app/views/partials/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
  <h4 class="pt-4">Shopping Cart</h4>
  <% if @cart.orderables.count > 0 %>
    <%= render "partials/orderables" %>
    <hr>
    <p>Total: <%= @cart.total%></p>
    <% if flash[:alert] %>
      <div class="alert alert-danger text-center p-2 mb-0" role="alert" id="show">
        <%= flash[:alert] %>
      </div>
    <% end %>
  <%else %>
    <p>Your cart is empty</p>
  <%end%>
<%end%>

app/views/partials/_footer.html.erb
<footer class="footer-set ">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h5 class="footer-head">Our Company</h5>
        <div class="footer-horizontal-rule mb-4"></div>
        <ul class="list-unstyled text-small">
          <li class="mb-1 "> <%= link_to "Delivery",root_path ,class:"footer-body" %>  </li>
          <li class="mb-1"> <%= link_to "Legal Notice",root_path ,class:"footer-body" %>  </li>
          <li class="mb-1"> <%= link_to "Terms and conditions",root_path ,class:"footer-body" %>  </li>
          <li class="mb-1"> <%= link_to "About us",root_path ,class:"footer-body" %>  </li>
          <li class="mb-1"> <%= link_to "Secure payment",root_path ,class:"footer-body" %>  </li>
        </ul>
      </div>
      <div class="col-md-4">
        <h5 class="footer-head">Products</h5>
        <div class="footer-horizontal-rule mb-4"></div>
        <ul class="list-unstyled text-small">
          <li class="mb-1"> <%= link_to "Prices drop",root_path ,class:"footer-body" %>  </li>
          <li class="mb-1"> <%= link_to "New products",root_path ,class:"footer-body" %>  </li>
          <li class="mb-1"> <%= link_to "Best sales",root_path ,class:"footer-body" %>  </li>
          <li class="mb-1"> <%= link_to "Contact us",root_path ,class:"footer-body" %>  </li>
          <li class="mb-1"> <%= link_to "Sitemap",root_path ,class:"footer-body" %>  </li>
        </ul>
      </div>
      <div class="col-md-4">
        <h5 class="footer-head" >Store Information</h5>
        <div class="footer-horizontal-rule mb-4"></div>
        <ul class="list-unstyled text-small">
          <li class="mb-1 add-design"> ShopOnline-Lahore </li>
          <li class="mb-1 add-design"> 000-000-0000</li>
          <li class="mb-1 add-design"> sales@shoponline.com </li>
        </ul>
      </div>
    </div>
  </div>
</footer>
<div class="footer-rights">
  <div class="container>
    <div class="row">
      <div class="col-12">
        <p class="text-center text-small mb-0"> Copyrights © 2024 ShopOnline. All Rights Reserved.</p>
      </div>
    </div>
  </div>
</div>

app/views/partials/_header.html.erb
<div class="header-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= link_to root_path, class: "home-link" do %>
          <h2 class="logo-design">S.Online</h2>
        <% end %>
      </div>
      <div class="col-md-4 ">
        <%= form_for "",url:root_path, role:"search", method: :get do %>
          <div class="input-group mb-3 rounded-pill search-bar-border">
            <%= text_field_tag :search, @search_term, placeholder: "Search Products Here...", class: "form-control search-focus  rounded-pill border-0  shadow-none" %>
            <div class="input-group-append">
              <button type="submit" class="btn btn-custom search-bar-btn rounded-pill ">
                <i class="fas fa-search search-icon-format"></i>
              </button>
            </div>
          </div>
        <%end%>
      </div>
      <div class="col-md-4 text-md-end header-cred-design mt-1">
        <%= link_to new_order_path, class:"cart-design home-login-link " do %>
          <i class="fa fa-shopping-cart"></i>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to "Logout" , destroy_user_session_path, data: {turbo_method: :delete} , class:"home-login-link admin-header-link  me-3"%>
          <% if current_user.has_role?(:Admin) %>
            <%= link_to "Admin", admin_path, class:"home-login-link"%>
          <%end%>
          <% if current_user.has_role?(:Vendor) %>
            <%= link_to "Vendor", vendors_home_index_path, class:"home-login-link "%>
          <%end%>
          <% if current_user.has_role?(:User) %>
            <%= link_to "User", root_path, class:"home-login-link "%>
          <%end%>
        <% else %>
          <%= link_to "Login" , new_user_session_path , class:"home-login-link me-3"%>
          <%= link_to "Register" , new_user_registration_path , class:"home-login-link"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_order.html.erb
<h4 class="text-center mt-4">Admin Orders</h4>
<table class="table table-striped border  ">
  <thead>
    <tr class="tbl-bg">
      <th scope="col" class="text-center ">Name</th>
      <th scope="col" class="text-center">Email</th>
      <th scope="col" class="text-center">Contact#</th>
      <th scope="col" class="text-center">Country</th>
      <th scope="col" class="text-center">State</th>
      <th scope="col" class="text-center">City</th>
      <th scope="col" class="text-center">Area</th>
      <th scope="col" class="text-center">Zip#</th>
      <th scope="col" class="text-center">Address</th>
      <th scope="col" class="text-center">Status</th>
      <th scope="col" class="text-center">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td class="text-center font-set align-middle"><%= order.user.username %></td>
        <td class="text-center font-set align-middle"><%= order.user.email %></td>
        <td class="text-center font-set align-middle"><%= order.phone_number %></td>
        <td class="text-center font-set align-middle"><%= order.country %></td>
        <td class="text-center font-set align-middle"><%= order.state %></td>
        <td class="text-center font-set align-middle"><%= order.city %></td>
        <td class="text-center font-set align-middle"><%= order.area %></td>
        <td class="text-center font-set align-middle"><%= order.zip_code %></td>
        <td class="text-center font-set align-middle"><%= order.adress %></td>
        <td class="text-center font-set align-middle"><%= order.status %></td>
        <td class="text-center align-middle "><%= link_to "View" ,order_path(order) ,class:"text-decoration-none px-2 edit-clr" %><%= link_to "Edit" ,edit_order_path(order) ,class:"text-decoration-none px-2 edit-clr" %>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/partials/_orderables.html.erb
<% @cart.orderables.each do |orderable|%>
  <% product = orderable.product%>
  <div id="<%= "cart-#{product.id}" %>">
    <hr>
    <div class="row pb-2">
      <div class="col-2">
        <%= image_tag product.avatar ,width:"70px"%>
      </div>
      <div class="col-3 pt-2">
        <%= product.title%>
      </div>
      <div class="col-2 pt-2">
        $<%= product.price %>
      </div>
      <div class="col-3 text-center pt-2">
        <%= form_with(url: add_orderables_path, id: "order_form", data: { turbo: true }) do |p| %>
          <%= p.hidden_field :id, value: product.id %>
          <%= p.number_field  :quantity, value: orderable.quantity, min: 0, class: "small-number-field text-center", onchange: "this.form.requestSubmit();" %>
          <%= p.submit "Submit", style: "display: none;" %>
        <% end %>
      </div>
      <div class="col-2 pt-2">
        <%= form_with(url: remove_orderables_path) do |p| %>
          <%= p.hidden_field :id, value: orderable.id %>
          <%= p.submit "X" ,class:"remove-cart"%>
        <% end %>
      </div>
    </div>
  </div>
<%end%>

app/views/partials/_product.html.erb
<%= link_to "New Product", new_product_path, class: "nav-link new-product-link  fw-bold text-end" %>
<table class="table table-striped border">
  <thead>
    <tr class="tbl-bg">
      <th scope="col" class="text-center">Name</th>
      <th scope="col" class="text-center">Price</th>
      <th scope="col" class="text-center">Quantity</th>
      <th scope="col" class="text-center">Image</th>
      <th scope="col" class="text-center">Detail</th>
      <th scope="col" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |f| %>
      <tr>
        <td class="text-center align-middle"><%= f.title %></td>
        <td class="text-center align-middle"><%= f.price %></td>
        <td class="text-center align-middle"><%= f.quantity %></td>
        <td class="text-center align-middle"><%= image_tag f.avatar ,width:"70px"%></td>
        <td class="text-center align-middle"><%= f.description %></td>
        <td class="text-center align-middle"><%= link_to "View" ,product_path(f) ,class:"text-decoration-none px-2 edit-clr" %> <%= link_to "Edit" ,edit_product_path(f) ,class:"text-decoration-none px-2 edit-clr" %>
          <%= link_to "Delete" ,product_path(f),class:"text-decoration-none edit-clr", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/partials/_productform.html.erb
<style>
  body{
  background-color: #f5f5f5;
  }
</style>
<div>
  <div class="container pt-3">
    <div class="row">
      <div class="col-md-2">
      </div>
      <div class="col-md-6">
        <%= form_with model: @product do |f| %>
          <div class="form-group">
            <%= f.label :title ,class:"label-set"%>
            <%= f.text_field :title, class: "input-lg custom-height form-control input-lg", placeholder:"Product name ..." %>
            <% if @product.errors[:title].any? %>
              <div class="text-danger">
                <%= @product.errors[:title].first %>
              </div>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :price ,class:"label-set" %>
            <%= f.text_field :price, class: "input-lg custom-height form-control",placeholder:"Product price ..." %>
            <% if @product.errors[:price].any? %>
              <div class="text-danger">
                <%= @product.errors[:price].first %>
              </div>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :quantity,class:"label-set" %>
            <%= f.text_field :quantity, class: "input-lg custom-height form-control",placeholder:"Product quantity ..." %>
            <% if @product.errors[:quantity].any? %>
              <div class="text-danger">
                <%= @product.errors[:quantity].first %>
              </div>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :Image,class:"label-set" %>
            <%= f.file_field :avatar, class: "input-lg  form-control"%>
            <% if @product.errors[:avatar].any? %>
              <div class="text-danger">
                <%= @product.errors[:avatar].first %>
              </div>
            <% end %>
          </div>
          <div class="form-group pb-3">
            <%= f.label :description,class:"label-set" %>
            <%= f.text_area :description, class: "form-control",rows:"4",placeholder:"Description ..." %>
            <% if @product.errors[:description].any? %>
              <div class="text-danger">
                <%= @product.errors[:description].first %>
              </div>
            <% end %>
          </div>
          <%= f.submit class:'btn btn-danger d-block mx-auto'%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/partials/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0  bg-body-tertiary mt-3" >
  <% if current_user.has_role?("Admin") ||  current_user.has_role?("Vendor") %>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <%= link_to "Dashboard", admin_path, class: "sidebar-nav-link nav-link #{'active bg-danger' if current_page?(admin_path)}" %>
      </li>
      <li>
        <%= link_to "Products", products_path, class:" sidebar-nav-link nav-link #{'active bg-danger' if current_page?(products_path)}" %>
      </li>
      <li>
        <%= link_to "Orders", orders_path, class: "sidebar-nav-link nav-link #{'active bg-danger' if current_page?(orders_path)}" %>
      </li>
    </ul>
  <% end %>
  <% if current_user.has_role?("Admin") %>
    <ul class="nav nav-pills flex-column mb-auto">
      <li>
        <%= link_to "Vendors", vendors_path, class: "sidebar-nav-link nav-link #{'active bg-danger' if current_page?(vendors_path)}" %>
      </li>
    </ul>
  <% end %>
</div>

app/views/partials/_vendor.html.erb
 <%= link_to "New Vendor", new_vendor_path, class: "nav-link new-product-link text-end fw-bold" %>
<table class="table table-striped border">
  <thead>
    <tr class="tbl-bg">
      <th scope="col" class="text-center">Name</th>
      <th scope="col" class="text-center">Email</th>
      <th scope="col" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |f| %>
      <tr>
        <td class="text-center align-middle"><%= f.username %></td>
        <td class="text-center align-middle"><%= f.email %></td>
        <td class="text-center align-middle"><%= link_to "View Order" ,vendor_path(f) ,class:"text-decoration-none px-2 edit-clr" %><%= link_to "Edit" ,edit_vendor_path(f) ,class:"text-decoration-none px-2 edit-clr" %>
          <%= link_to "Delete" ,vendor_path(f),class:"text-decoration-none px-2 edit-clr", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %><%= link_to "View Product" ,vendorproduct_path(f) ,class:"text-decoration-none px-2 edit-clr" %>
        </tr>
      <%end%>
    </tbody>
  </table>

app/views/partials/_vendorform.html.erb
<style>
  body{
  background-color: #f5f5f5;
  }
</style>
<div>
  <div class="container pt-5">
    <div class="row">
      <div class="col-md-2">
      </div>
      <div class="col-md-6">
        <%= form_with model: @user, url: vendors_path do |f| %>
          <div class="form-group">
            <%= f.label :username, class:"label-set" %>
            <%= f.text_field :username, class: "input-lg custom-height form-control", placeholder:"Enter name ..." %>
            <% if @user.errors[:username].any? %>
              <div class="text-danger">
                <%= @user.errors[:username].first %>
              </div>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :email, class:"label-set" %>
            <%= f.text_field :email, class: "input-lg custom-height form-control",placeholder:"Enter email ..." %>
            <% if @user.errors[:email].any? %>
              <div class="text-danger">
                <%= @user.errors[:email].first %>
              </div>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :password, class:"label-set" %>
            <%= f.text_field :password,type:'password', class: "input-lg custom-height form-control",placeholder:"Enter Password..." %>
            <% if @user.errors[:password].any? %>
              <div class="text-danger">
                <%= @user.errors[:password].first %>
              </div>
            <% end %>
          </div>
          <%= f.submit class:'mt-2 btn btn-danger d-block mx-auto'%>
        <%end%>
      </div>
    </div>
  </div>
</div>